### ISSUE TITLE
Support compressed/encrypted log files (.MFC, .MFE, .MFM)

### ISSUE THREAD

**Issue by MatinF** [CSS-Electronics/api-examples#1]
**Outline the feature request** 
Support native handling of compressed/encrypted log files from the CANedge within the `canedge_browser` module and the `mdf_iter` module. 

**What is the use case?**
This would enable native support for all types of CANedge log files, removing the need for using the MDF4 converters as part of Python automation scripts.

Please comment if you'd like to see this feature added as well, or if you have any thoughts on it.

**Comment by fandrewfox** [comment]
This is a great idea. We're logging uncompressed files for now, but it would be nice to reduce network traffic and storage requirements by more than 70%.

**Comment by Sp0b1e** [comment]
Hi @MatinF,
what is the status on native support for compresed log files in `mdf_iter`?

**Comment by MatinF** [comment]
Support for MFC, MFE and MFM files have now been added in the mdf_iter and canedge_browser Python API modules. The api-examples and dashboard-writer repositories have been updated accordingly.
