### ISSUE TITLE
requirements installation problem

### ISSUE THREAD

**Issue by yozdas** [CSS-Electronics/api-examples#13]
i tried to install requirements with "pip install -r requirements.txt", first i had problem with numpy version, i changed to latest version then i had problem with wheel "ERROR: Could not build wheels for multidict, pandas, yarl, which is required to install pyproject.toml-based projects" as suggested on internet i upgraded pip.
here is error log file:
[errors.txt](https://github.com/CSS-Electronics/api-examples/files/8053604/errors.txt)
how can i fix these errors?

**Comment by MatinF** [comment]
Can you let us know your OS and Python version?

**Comment by yozdas** [comment]
Python Version: Python 3.10.2
OS: Ubuntu 20.04.3 LTS
IDE: vscode and PyCharm
i think i solved the issue by modifying versions of packages in requirements.txt which is attached.
[requirements2.txt](https://github.com/CSS-Electronics/api-examples/files/8053931/requirements2.txt)

**Comment by MatinF** [comment]
Our api modules and examples are not built for Python 3.10 - please use one of the supported versions listed in the readme
