### ISSUE TITLE
mdf-iter on arm architecture

### ISSUE THREAD

**Issue by TomasRyss** [CSS-Electronics/api-examples#20]
Hello CSS team,

First of all, let me state that i am amateur in Python and coding stuff.

But recently I have tried to set up server and dashboard on local network (localy hosted) on our raspberry pi 4B at our workplace.

I have managed to set up local minio server (CanEdge2 succesfully sent data to the server.), influxdb writer and grafana dashboard but recently hit an obstacle when I tried to install mdf-iter 2.0.5 .

From what I see in download files the package is compiled only for x86 architecture. 

Is there any way how to install this package to arm architecture, or how to compile it to it?  

Thank you in advance

best regards

Tomas

**Comment by MatinF** [comment]
You can try this build 
[mdf_iter-2.0.5-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64 (1).zip](https://github.com/CSS-Electronics/api-examples/files/11114955/mdf_iter-2.0.5-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.1.zip)
