### ISSUE TITLE
Possibility to read CAN raw data

### ISSUE THREAD

**Issue by b-r-you-know** [CSS-Electronics/api-examples#3]
Is it possible to load *.ASC files or are only *.MF4 files supported?

**Comment by MatinF** [comment]
Only bus logging MF4 files from the CANedge are currently supported. However, if you load ASC files into a pandas dataframe with the right structure, you could use the tools that take such an input.

Is this regarding usage together with a CANedge or something else?

**Comment by b-r-you-know** [comment]
Thanks for the quick reply

To be honest I found via your great introduction videos to the github repo
https://www.csselectronics.com/screen/page/simple-intro-j1939-explained

Currently I'm logging with different brand loggers (cause I did not know about yours)

I would like to ask you what kind of format the pandas dataframe needs to have?

Basically I want to extract DM01 (Diagnostic-Messages) from J1939 frames which are send using transport protocol. And I struggle repacking Transport Protocol Messages from the raw *.ASC file

**Comment by MatinF** [comment]
Hi again

You can find details on this in the readme files of the individual api modules. We’re unfortunately not able to provide technical support on integrating other devices than our own - but you’re welcome to reach out to us via contact@csselectronics.com if you wish to try out a CANedge for your use case.
