### ISSUE TITLE
Hardcoded resampling argument

### ISSUE THREAD

**Issue by sorenmik** [CSS-Electronics/api-examples#4]
https://github.com/CSS-Electronics/api-examples/blob/8db4fbc44f727f5bf995f45cca028d6b962eae93/examples/data-processing/utils.py#L87

It seems the resampling argument is hardcoded to "1S" instead of using "res"? 

The problem is also present in "dashboard-writer"-repo, "utils.py".

**Comment by MatinF** [comment]
Thanks for reporting, this has been fixed now
