### ISSUE TITLE
Random (?) call ".to_csv" in method restructure_data()

### ISSUE THREAD

**Issue by sorenmik** [CSS-Electronics/api-examples#5]
https://github.com/CSS-Electronics/api-examples/blob/e5cd85ec05b328c619fed85985f068c2da3a02ce/examples/data-processing/utils.py#L92

It seems kinda out of place that the method "restructure_data()" outputs a .csv file.

In the example "process_data.py", there is a specific call to .to_csv() after restructure_data(), resulting in a write and then an overwrite of the .csv file:

"process_data.py":
df_phys_join = restructure_data(df_phys=df_phys_all, res="1S")  ### Writes .csv file
df_phys_join.to_csv("output_joined.csv") ### Overwrites the above csv file

Same issue in repo "dashboard-writer"

**Comment by MatinF** [comment]
You're right, thanks again for the report - it should be updated now

**Comment by sorenmik** [comment]
No problem - thank you for all the great tools.
